### ISSUE TITLE
[TASK] Add recover method to the TokenWrapper and TokenWrapperHandler

### ISSUE THREAD

**Issue by drewstone** [webb-tools/protocol-solidity#100]
# SPEC

We need a way to recover tokens that are custodied by the TokenWrapper smart contract after usage of the wrapping fee mechanism. Right now, the wrapping fee is sent to the TokenWrapper, but there is no way to send these tokens out of the contract. They are effectively locked.

A similar idea was implemented here: https://github.com/tornadocash/tornado-nova/blob/master/contracts/TornadoPool.sol#L172

## Implementation
The function `rescueTokens` does the following:
- [x] Takes in four parameters: `address tokenAddress`, `address payable to`, `uint256 amountToRescue`, `uint256 nonce`.
- [x] If `tokenAddress` is 0 and `amountToRescue` is less than or equal to native ETH balance of `TokenWrapper` then it sends `amountOfRescue` ETH to `to`.
- [x] If `tokenAddress` is 0 and `amountToRescue` is greater than native ETH balance of `TokenWrapper` then it sends `address(this).balance` ETH to `to`.
- [x] If `tokenAddress is non-zero, then it is an ERC20 token address. If `IERC20(tokenAddress).balanceOf(address(this))` is less than or equal to `amountToRescue` then it sends `amountToRescue` tokens to `to`.
- [x] If `tokenAddress is non-zero, then it is an ERC20 token address.  If `IERC20(tokenAddress).balanceOf(address(this))` is greater than `amountToRescue` then it sends all of its tokens to `to`.
- [x] Properly handle the nonce incrementation. 

The implementation of the function is here: 

```
    function rescueTokens(address tokenAddress, address payable to, uint256 amountToRescue, uint256 nonce) public onlyGovernor {
        require(to != address(0), "Cannot send liquidity to zero address");
        require(tokenAddress != address(this), "Cannot rescue wrapped asset");
        require(proposalNonce < nonce, "Invalid nonce");
        require(nonce <= proposalNonce + 1, "Nonce must increment by 1");

        if (tokenAddress == address(0)) {
            // Native Ether 
            uint256 ethBalance = address(this).balance;
            if(ethBalance >= amountToRescue) {
                to.transfer(amountToRescue);
            } else {
                to.transfer(ethBalance);
            }
            
        } else {
            // ERC20 Token
            uint256 erc20Balance = IERC20(tokenAddress).balanceOf(address(this));
            if(erc20Balance >= amountToRescue) {
                IERC20(tokenAddress).transfer(to, amountToRescue);
            } else {
                IERC20(tokenAddress).transfer(to, erc20Balance);
            }  
        }

        proposalNonce = nonce;
    }
```

The proposal format is here:

**Comment by drewstone** [comment]
New updates from recent discussion:
- Add a `address feeRecipient` to the `TokenWrapper.sol` contract.
- Add a `setFeeRecipient` to the `GovernedTokenWrapper.sol` contract.
- Add a new proposal to the DKG `setFeeRecipient` and add to the spec.
- Add rescue tokens to the `Bridge` using a sub-contract called Treasury.
```
contract Treasury {
	function rescueTokens(...) {}
}
```

**Comment by saiakilesh** [comment]
Assume we choose to send the fee to the bridge directly, as described in the post above.

There are two options for how we control who can call the `rescueTokens` function:

1. `rescueTokens` can be called by an authorized, whitelisted set of users. The set of authorized users is set through DKG proposals.
2. `rescueTokens` itself can only be executed via proposal, similar to `updateEdge, setFee, addToken, setFeeRecipient, etc...`

I think (2) might be better than (1). The reason is that we may want to whitelist a certain user Alice to `rescueTokens` at some point in time, but Alice may abuse her power at some later point in time and `rescueTokens` to herself when she is not meant to. Therefore, we have to be careful to keep track and de-whitelist (unauthorize) Alice right after. Or we have to keep track of timestamps and say Alice can only `rescueTokens` up till a certain timestamp. This seems like too much upkeep. Instead, if we just have the DKG vote on who tokens should be rescued to, the system can work in a much more trustless/clean manner.  

The only disadvantage I can think of for (2) is that we would need to make a DKG proposal every time we want to rescue tokens and that might be inefficient (though, I'm not sure)?

**Comment by drewstone** [comment]
(1) is definitely not a good idea. I think you outlined why it is not a good idea and I'd be certain to underline even more deeply that whitelisting users to transfer funds out of contracts is definitely not a good idea.

Given (2) is the route to go, can you spec up how you would implement this? If using a sub-contract seems unnecessary, I'd just go ahead and implement a `rescueTokens` function directly on the bridge contract. If you have other ideas definitely share here.

**Comment by saiakilesh** [comment]
#Implementation SPEC:

I think using a subcontract seems unnecessary. As you wrote we can put `rescueTokens` directly on the bridge contract. It will look like:

```
uint32 rescueTokensNonce;

function rescueTokens(bytes calldata data, bytes memory sig) external signedByGovernor(keccak256(data), sig) {
    nonce = data[36:40];
    tokenAddress = data[40:60];
    to = data[60:80];
    amountToRescue = data[80:112];

    require(to != address(0), "Cannot send liquidity to zero address");
    require(tokenAddress != address(this), "Cannot rescue wrapped asset");
    require(rescueTokensNonce < nonce, "Invalid nonce");
    require(nonce <= rescueTokensNonce + 1, "Nonce must increment by 1");

    if (tokenAddress == address(0)) {
        // Native Ether 
        uint256 ethBalance = address(this).balance;
        if(ethBalance >= amountToRescue) {
            to.transfer(amountToRescue);
        } else {
            to.transfer(ethBalance);
        }
        
    } else {
        // ERC20 Token
        uint256 erc20Balance = IERC20(tokenAddress).balanceOf(address(this));
        if(erc20Balance >= amountToRescue) {
            IERC20(tokenAddress).transfer(to, amountToRescue);
        } else {
            IERC20(tokenAddress).transfer(to, erc20Balance);
        }  
    }

    rescueTokensNonce = nonce;
}
    
```

I added the format of the proposal data here: https://github.com/webb-tools/protocol-solidity/issues/83

**Comment by dutterbutter** [comment]
Closing as this work has been completed.
