### ISSUE TITLE
[TASK] Update VAnchor.ts to pass in ZK components

### ISSUE THREAD

**Issue by nepoche** [webb-tools/protocol-solidity#120]
The VAnchor class has statements which reference file paths. These references couple the functionality of the VAnchor with the location of files. Projects without a local `protocol-solidity-fixtures` will fail to import the `@webb-tools/anchors` package. Instead, we should pass in ZKComponents similar to Anchor.ts.

**Comment by saiakilesh** [comment]
lol I didn't even know this was a task.

i needed it for the e2e tests so I completed it.
