### ISSUE TITLE
[TASK] Move circom proving to sdk-core

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-solidity#157]
## Overview

Currently the DApp depends on the protocol-solidity for proving when it should really depend directly on `sdk-core`. Unifying the proving functionality to the api will be much cleaner and a simpler dependency. 

### Tasks  

- [ ] Review files within `packages/utils` to determine complete list of files to be moved to sdk-core
- [ ] Move `Utxo.ts` to sdk-core

**Comment by dutterbutter** [comment]
@nepoche please provide additional details / clarity where applicable.

**Comment by nepoche** [comment]
This task is intended to unify proving - and utilities which aid in proving - to `@webb-tools/sdk-core`.

`@webb-tools/merkle-tree` in protocol-solidity will be moved to sdk-core, as well as typescript classes for Utxo and Keypair. 

Wrapper classes in `@webb-tools/anchors` will be changed in the following ways:
- a member variable will be added for a ProvingManager
- functions such as proveAndVerify will delegate to the class's ProvingManager.

The current proving in `sdk-core` will be changed in the following ways:
- current `ProvingManager` and `ProvingManagerWrapper` classes will be renamed to `ArkworksProvingManager` and `ArkworksProvingManagerWrapper` respectively.
- New Implementations for `CircomProvingManager` and `CircomProvingManagerWrapper` will be created.
- Investigate ways to unify the arkworks and circom proving manager classes under a single interface.
