### ISSUE TITLE
[SPEC] Integrate Signature Bridge functionality for VAnchors into classes

### ISSUE THREAD

**Issue by saiakilesh** [webb-tools/protocol-solidity#94]
# Overview
Currently, the VAnchors cannot be updated using the `SignatureBridge.sol` contract. This SPEC outlines how to amend the TypeScript classes to make this functionality possible.

# Functions to add/modify in `SignatureBridgeSide.ts`
We propose to change the function signatures of the following functions to also take in a VAnchor:
```
public async createAnchorUpdateProposalData(srcAnchor: Anchor | VAnchor, executionResourceID: string): Promise<string>

public async createHandlerUpdateProposalData(anchor: Anchor | VAnchor, newHandler: string): Promise<string>

public async connectAnchorWithSignature(anchor: Anchor | VAnchor): Promise<string>

public async setResourceWithSignature(anchor: Anchor | VAnchor): Promise<string>

public async executeHandlerProposalWithSig(anchor: Anchor | VAnchor, newHandler: string)

public async executeAnchorProposalWithSig(srcAnchor: Anchor | VAnchor, executionResourceID: string)
```

# Modifications to `VBridge.ts`
We propose to modify `VBridge.ts` to work with either a `SignatureBridgeSide` or a `VBridgeSide`. At any place in the code where a `VBridgeSide` is currently used, we instead have to check the type and invoke the correct function. For instance, the following for loop:
```
    for (let vAnchor of vAnchorsToUpdate) {
      // get the bridge side which corresponds to this anchor
      const chainId = await vAnchor.signer.getChainId();
      const resourceID = await vAnchor.createResourceId();
      const vBridgeSide = this.vBridgeSides.get(chainId);

      await vBridgeSide!.voteAnchorProposal(srcAnchor, resourceID);
      await vBridgeSide!.executeProposal(srcAnchor, resourceID);
    }
```
will change to something like:
```
    for (let vAnchor of vAnchorsToUpdate) {
      // get the bridge side which corresponds to this anchor
      const chainId = await vAnchor.signer.getChainId();
      const resourceID = await vAnchor.createResourceId();
      const vBridgeSide = this.vBridgeSides.get(chainId);
      if (typeOf(vBridgeSide) == VBridgeSide) {
        await vBridgeSide!.voteAnchorProposal(srcAnchor, resourceID);
        await vBridgeSide!.executeProposal(srcAnchor, resourceID);
      } else {
        await vBridgeSide!.executeAnchorProposalWithSig(srcAnchor, resourceID);
      }
    }
```
I am not sure if this is the cleanest way to do things...it may just be better to have a `SignatureVBridge.ts` class.

**Comment by drewstone** [comment]
This is good. Another potentially better way is to use a generic interface that implements some shared methods such as `handleProposalAction` which the `VBridgeSide` and `SignatureBridgeSide` can implement. This way instead of using `Anchor | VAnchor`, etc, we use something like `IAnchor` and `IBridgeSide` which implement these shared methods.

Then, we can implement the `VBridge` over these interfaces.
